---
- name: Install python3, docker, docker-compose
  hosts: tag_Name_dev_server
  become: yes
  gather_facts: False
  tasks:
    - name: Install python3 and  docker
      vars:
        ansible_python_interpreter: /usr/bin/python3.7
      ansible.builtin.yum: 
        name: 
          - python3
          - docker
        update_cache: yes
        state: present
    - name: Install Docker-compose
      ansible.builtin.get_url: 
        url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: Start docker daemon
      ansible.builtin.systemd:
        name: docker
        state: started
    - name: Install docker python module
      ansible.builtin.pip:
        name: 
          - docker
          - docker-compose
          - urllib3==1.26.6


- name: Create new linux user
  hosts: tag_Name_dev_server
  become: yes
  tasks: 
    - name: Create new linux user
      ansible.builtin.user:
        name: dato
        groups: adm,docker



- name: Start docker containers
  hosts: tag_Name_dev_server
  become: yes
  become_user: dato
  vars_files:
    - project-vars
  tasks:
    - name: Copy docker compose
      ansible.builtin.copy:
        src: /home/dato/Desktop/for_devops/docker-compose.yaml
        dest: /home/dato/docker-compose.yaml
    - name: Docker login  
      community.docker.docker_login: 
        registry_url: https://index.docker.io/v1/
        username: datoxx
        password: "{{docker_password}}"
    - name: Start container from compose
      community.docker.docker_compose: 
        project_src: /home/dato